apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWWhwUE9GM2pGVGd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU16QXhOekUxTURCYUZ3MHpOVEE1TWpneE56SXdNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURHYjI4RGV1QzBMODV1NmtTbmRHSTRNajlqMWFZQ3VsRmVQRzlsQWsvTU9LS3FLalVnWmE4S2RMbGkKTVM0QlRQUW45c0t3bEgvM1hRd0p2WW5JYm5WZnJoWHc0K0lzOTg1U2Z2THA2YVd1NmUweHZVa1pIZVhHNi9jSwpWVjU0bnhEZ3NkRnkrQVhma3lZTk9qUGZ4WkIyS3IvTHQ1a3VCUU1PenNyQlkyRWY1TWRIRlNyRjJ5aDNWRFRCClQ1SllJMVMya2EybXRSVHo0dFh6S2ZkNGRiZnY4Y2FjbTdpbzdqY2J1YVFhdjRyd0QveFJLTi9ocG1Rc2xHVkUKL1JpSVJ5eElPOUdQalBOWmZFZVFFeG1RME83S0FJNkdlQ0hjQzhwdjVCczgyeWVuY3RzL1hmS3o5eFJJL1hsdAo1QUZWV3VmalN3SDBaSWVUNERVNVBhTmNrdE1OQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSc3gyay9rZ2JjTkREZFZ0RE9WQlVvYVFTajREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTdDRDd1bm5GKwoyK3hLVHRmV0YzOHh0UHpqN1RpVHZOTmZUelhDZytGYU11Yyt4cGNLSUNqWkN3aVBuYnhhZkRaa0JuWmUrUkJ3CjRncXVBZFpVL2VDM0FLdnJlUk80Ykx0ZnNhU1ZXa3ZPM0JicDlVc2d5a1ZGajFLWVpRbVFlUmI0RU5PbGpjNVEKWG55a3VOZ2Nmc1JRQkp5RUJJKzhYeFVoWFFRTmo2bFUwSVNuMDk3Ny9OUFptZklJb1NWMVc2VG9OdU82V0ExWgpmc2I0dEV3K3M1MU1uTTd4OEZvKzNrdks0QXVKUmF6K29yK0I1ZzY4MFVSS0xzQVd2cnRDd2pTbWd4Wlg4N2t4ClJXRTNVOW1vVEFmc0ZGQ3ZZZ2Vvbnc2VEVMbjFNV2s2RVhwZ2U2WjhDVjdjTkcxSEZGNDNkcE9iRk5KZkp5QVIKQUttNWQxWUdOdTU3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://B21A6E4F833B9899088AD07FAA17ED91.gr7.us-east-1.eks.amazonaws.com
  name: my-eks-cluster
contexts:
- context:
    cluster: my-eks-cluster
    user: my-eks-cluster
  name: my-eks-cluster
current-context: my-eks-cluster
users:
- name: my-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - my-eks-cluster
        - --region
        - us-east-1