apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: default
imagePullSecrets:
- name: cloudsmith-regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: default
type: Opaque
stringData:
  secret-key: "your-secret-key-change-this-in-production"